# Numpy Matrix Operations

<img src="Matrix.png" alt="Image of Matrix Example" style="height:350px;">

![Demo Image](Matrix.png "Optional title text")

In [3]:
import numpy as np

In [4]:
q1_sales = np.array(
    [
        [60,10,90,40], # Iphone units sold in K
        [45,20,60,45],
        [1,70,20,25]
    ]
)
q1_sales

array([[60, 10, 90, 40],
       [45, 20, 60, 45],
       [ 1, 70, 20, 25]])

In [5]:
q2_sales = np.array(
    [
        [40,5,100,60], # Iphone units sold in K
        [50,20,75,30],
        [0,80,10,15]
    ]
)
q2_sales

array([[ 40,   5, 100,  60],
       [ 50,  20,  75,  30],
       [  0,  80,  10,  15]])

## Sum of product sold in both quarters

In [6]:
q1_sales + q2_sales

array([[100,  15, 190, 100],
       [ 95,  40, 135,  75],
       [  1, 150,  30,  40]])

## Sales unit growth from q1 to q2

In [7]:
q2_sales - q1_sales

array([[-20,  -5,  10,  20],
       [  5,   0,  15, -15],
       [ -1,  10, -10, -10]])

## Percentage growth in sales from q1 to q2 

In [8]:
((q2_sales - q1_sales) / q1_sales) * 100

array([[ -33.33333333,  -50.        ,   11.11111111,   50.        ],
       [  11.11111111,    0.        ,   25.        ,  -33.33333333],
       [-100.        ,   14.28571429,  -50.        ,  -40.        ]])

# Revenue

In [9]:
unit_price = np.array([
    [100, 80, 65, 70],
    [80, 60, 62, 65],
    [85, 40, 55, 59]
])
unit_price

array([[100,  80,  65,  70],
       [ 80,  60,  62,  65],
       [ 85,  40,  55,  59]])

In [11]:
q1_sales

array([[60, 10, 90, 40],
       [45, 20, 60, 45],
       [ 1, 70, 20, 25]])

In [10]:
revenue_q1 = q1_sales * unit_price
revenue_q1

array([[6000,  800, 5850, 2800],
       [3600, 1200, 3720, 2925],
       [  85, 2800, 1100, 1475]])

In [12]:
marketing = 0.2 # 20 percent each product
q1_expenditure_marketing = revenue_q1 * marketing
q1_expenditure_marketing

array([[1200.,  160., 1170.,  560.],
       [ 720.,  240.,  744.,  585.],
       [  17.,  560.,  220.,  295.]])

In [13]:
net_revenue = revenue_q1 - q1_expenditure_marketing
net_revenue

array([[4800.,  640., 4680., 2240.],
       [2880.,  960., 2976., 2340.],
       [  68., 2240.,  880., 1180.]])

# Product Of Matrices

In [15]:
rooms = np.array([
    [1200, 2],
    [2500,3]
])
rooms

array([[1200,    2],
       [2500,    3]])

In [16]:
pricing = np.array([800, 25000])
pricing

array([  800, 25000])

In [17]:
print(1200*800 + 25000*2)

1010000


In [18]:
print(2500*800 + 25000*3)

2075000


In [19]:
np.dot(rooms, pricing)

array([1010000, 2075000])