# Numpy Matrix Operations

<img src="Matrix.png" alt="Image of Matrix Example" style="height:350px;">

![Demo Image](Matrix.png "Optional title text")

In [3]:
import numpy as np

In [4]:
q1_sales = np.array(
    [
        [60,10,90,40], # Iphone units sold in K
        [45,20,60,45],
        [1,70,20,25]
    ]
)
q1_sales

array([[60, 10, 90, 40],
       [45, 20, 60, 45],
       [ 1, 70, 20, 25]])

In [5]:
q2_sales = np.array(
    [
        [40,5,100,60], # Iphone units sold in K
        [50,20,75,30],
        [0,80,10,15]
    ]
)
q2_sales

array([[ 40,   5, 100,  60],
       [ 50,  20,  75,  30],
       [  0,  80,  10,  15]])

## Sum of product sold in both quarters

In [6]:
q1_sales + q2_sales

array([[100,  15, 190, 100],
       [ 95,  40, 135,  75],
       [  1, 150,  30,  40]])

## Sales unit growth from q1 to q2

In [7]:
q2_sales - q1_sales

array([[-20,  -5,  10,  20],
       [  5,   0,  15, -15],
       [ -1,  10, -10, -10]])

## Percentage growth in sales from q1 to q2 

In [ ]:
((q2_sales - q1_sales) / q1_sales) * 100