# Numpy Basics 

In [1]:
import numpy as np

In [2]:
arr = np.array([5,1,7,9,3])

arr

array([5, 1, 7, 9, 3])

In [3]:
arr.ndim

1

In [26]:
arr.shape

product_sold = np.array(
    [
        [ 25, 10, 18, 15], # iphone
        [40, 30, 5, 12], # Samsung
        [0, 60, 2, 10] # Huwaei
    ], dtype="int32"
) 

In [27]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [28]:
product_sold.ndim

2

In [29]:
product_sold.shape

(3, 4)

In [30]:
product_sold.dtype

dtype('int32')

In [34]:
product_sold[0][0].nbytes

4

In [33]:
product_sold.itemsize

4

In [35]:
product_sold.nbytes

48

In [37]:
product_sold.size

12

In [38]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [39]:
# Sorting

np.sort(product_sold)

array([[10, 15, 18, 25],
       [ 5, 12, 30, 40],
       [ 0,  2, 10, 60]], dtype=int32)

In [40]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [41]:
np.sort(product_sold, axis=0)

array([[ 0, 10,  2, 10],
       [25, 30,  5, 12],
       [40, 60, 18, 15]], dtype=int32)

In [42]:
np.sort(product_sold, axis=-1)

array([[10, 15, 18, 25],
       [ 5, 12, 30, 40],
       [ 0,  2, 10, 60]], dtype=int32)

In [46]:
np.sort(product_sold, axis=0)

array([[ 0, 10,  2, 10],
       [25, 30,  5, 12],
       [40, 60, 18, 15]], dtype=int32)

In [48]:
empty_zeros = np.zeros(shape=(3,5))
empty_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
empty_zeros.dtype

dtype('float64')

In [50]:
empty_zeros = np.zeros(shape=(3,5), dtype ="int32")
empty_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [52]:
empty_ones = np.ones((2,5))
empty_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
empty_ones.shape

(2, 5)

In [55]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [56]:
np.linspace(1,10).shape

(50,)

In [57]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
np.linspace(1,500,500)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [60]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [61]:
product_sold.sum()

np.int64(227)

In [63]:
product_sold.sum(axis=-1)

array([68, 87, 72])

In [64]:
product_sold.sum(axis=0)

array([ 65, 100,  25,  37])

In [65]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [66]:
reshaped = product_sold.reshape(12,1)
reshaped

array([[25],
       [10],
       [18],
       [15],
       [40],
       [30],
       [ 5],
       [12],
       [ 0],
       [60],
       [ 2],
       [10]], dtype=int32)

In [67]:
reshaped.reshape(4,3)

array([[25, 10, 18],
       [15, 40, 30],
       [ 5, 12,  0],
       [60,  2, 10]], dtype=int32)

In [69]:
reshaped.reshape(2,6)

array([[25, 10, 18, 15, 40, 30],
       [ 5, 12,  0, 60,  2, 10]], dtype=int32)

In [70]:
product_sold

array([[25, 10, 18, 15],
       [40, 30,  5, 12],
       [ 0, 60,  2, 10]], dtype=int32)

In [71]:
for row in product_sold:
    print("Row =",row)

Row = [25 10 18 15]
Row = [40 30  5 12]
Row = [ 0 60  2 10]


In [72]:
for row in product_sold:
    for value in row:
        print("Element =",value)

Element = 25
Element = 10
Element = 18
Element = 15
Element = 40
Element = 30
Element = 5
Element = 12
Element = 0
Element = 60
Element = 2
Element = 10


In [76]:
arr = np.array([16,81,4,26])
arr

array([16, 81,  4, 26])

In [77]:
np.sqrt(arr)

array([4.        , 9.        , 2.        , 5.09901951])

In [78]:
np.std(arr)

np.float64(29.4819860253681)